### ISSUE TITLE
Integration Test01    IT004

### ISSUE THREAD

**Issue by ghost** [budougumi0617/DesignPatternJava#5]
## Test No
IT004-7
IT004-8
IT004-9
IT004-10
IT004-11
## Procedure
送信文字列について、半角英数字と異常値（全角英数字、全角半角スペース、タブキー）の混合文字列を送信する。
## Expected result
エラーメッセージ「メッセージは半角英数字16文字までです。」ダイアログが表示される。
ＡｒｄｕｉｎｏのＬＣＤに文字列は表示されない。
入力値は初期化されずに残っている。
## Actual result
エラーダイアログは表示されない。
半角英数字と異常値の混合文字列がＬＣＤパネルに表示される。
入力値は初期化されずに残っている。
## Cause
CheckTextクラスのcheckBlankメソッドとcheckTypeメソッドの正規表現の記述に誤りがあった。
## Resolution
3a1512f
CheckTextクラスのcheckBlankメソッドとcheckTypeメソッドの正規表現を修正した。

単体テストのテストケースが足りていなかったため単体テストで発見できず統合テストで発見した。
単体テストに半角全角英数字混合のテストケースを追加して、修正後のコードに全クラスの単体テストを実行したところ合格した。
Build https://travis-ci.org/budougumi0617/DesignPatternJava/builds/171907276
この修正により他の機能への影響は出ていない。
## Rank
- [ ]  A
- [x]  B
- [ ]  C
- [ ]  要望

**Comment by budougumi0617** [comment]
Fixed this issue by #3, and #7.
