### ISSUE TITLE
Integration Test02 IT005

### ISSUE THREAD

**Issue by ghost** [budougumi0617/DesignPatternJava#6]
## Test No
IT005-12
## Procedure
Arduino側のボーレートの値を300にする。
アプリのパラメータは、Arduinoを接続しているCOMポート番号、ボーレートを300、文字列入力欄に「aaa」を入力して「送信」ボタンを押下する。
## Expected result
ArduinoのLCDパネルに送信した文字列が表示される。
入力値は初期化されずに残っている。
## Actual result
ArduinoのLCDパネルに送信した文字列が表示されない。
入力値は初期化されずに残っている。
## Cause
Arduino側のボーレートとアプリ側のボーレートを75～300の範囲に設定するとLCDパネルに文字列が表示されず、600～128000の範囲に設定すると表示されることを確認した。
75、110、134、150についてはArduino公式HPにて未対応であるとわかった。
https://www.arduino.cc/en/Serial/Begin
ボーレート300が送信できない点については原因不明。
## Resolution
要件定義提示元に合意を頂き、アプリのボーレート値は600～128000の数値に対応すると要件定義を変更した。
それに伴い、要求仕様書・評価項目書の内容を変更した。

- 要求仕様書
2.3.2 R-1.2 ボーレートを下限値600に変更
4.1.1 画面仕様をボーレートを下限値600に変更
- 評価項目書 
IT003-2 ボーレートを下限値600に変更
IT003-12 ボーレートの設定・正常値を300→600に変更

1bba1df
PanelBaudRateクラスのinitメソッド内、ボーレートを選択するコンボボックスの値範囲を600～128000に変更した。
修正後に全クラスの単体テストを実行したところ合格した。
Build https://travis-ci.org/budougumi0617/DesignPatternJava/builds/172487851
この修正により他の場所への影響は出ていない。
## Rank
- [ ]  A
- [ ]  B
- [x]  C
- [ ]  要望

**Comment by budougumi0617** [comment]
Fixed this issue by #3, and #7.
